title:              Pensieve
description:        'Linux, System Programming'
tagline:            'Linux, System Programming'
url:                https://nglee.github.io
baseurl:            ''
paginate:           5
timezone:           Asia/Seoul

author:
  name:             Namgoo Lee
  url:              https://nglee.github.io
  email:            lee.namgoo@sualab.com

version:            1.0.0

plugins:
    - jekyll-seo-tag

google_analytics_id: UA-117494839-1
